name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: myapp
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Path to the web app project folder

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: |
        cd Humongous.Healthcare.Web
        dotnet build --configuration Release

    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.3.x'
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: |
        cd Humongous.Healthcare.Web/ClientApp
        nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run MSBuild
      run: msbuild .\Humongous.Healthcare.Web\Humongous.Healthcare.Web.csproj
      
